In [15]:
import glob
import pandas as pd
path = "./database_model/API_data"
files = glob.glob(path + "/*.csv")
dataframe = pd.DataFrame()
content = []

In [16]:
for filename in files:
    df = pd.read_csv(filename, index_col = None)
    content.append(df)

In [23]:
files

['./database_model/API_data/waiting_periods.csv',
 './database_model/API_data/minors.csv',
 './database_model/API_data/gestational_limits.csv',
 './database_model/API_data/insurance_coverage.csv']

In [24]:
content

[   Kentucky  Oklahoma  Kansas  Ohio  Arizona  Mississippi  Tennessee  \
 0      24.0      72.0    24.0  24.0     24.0         24.0       48.0
 1       2.0       1.0     1.0   2.0      2.0          2.0        2.0
 2       NaN       NaN     NaN   NaN      NaN          NaN        NaN
 3       NaN       NaN     NaN   NaN      NaN          NaN        NaN
 4       NaN       NaN     NaN   NaN      NaN          NaN        NaN

    Wisconsin                                            Alabama  Missouri  \
 0       24.0                                                 48      72.0
 1        2.0                                                  1       2.0
 2        NaN  In cases of ectopic pregnancy or severe fetal ...       NaN
 3        NaN                                                NaN       NaN
 4        NaN                                                NaN       NaN

    ...                  Arkansas North Dakota                      Iowa  \
 0  ...                        72         24.0                        24
 1  ...                         2          1.0                         1
 2  ...                       NaN          NaN                       NaN
 3  ...  2019-11-13T12:13:26.000Z          NaN  2022-06-18T17:06:11.000Z
 4  ...                       NaN          NaN                       NaN

   Michigan  Nebraska                                       South Dakota  \
 0     24.0      24.0                                                 72
 1      1.0       1.0                                                  2
 2      NaN       NaN                                                NaN
 3      NaN       NaN                                                NaN
 4      NaN       NaN  Weekends and holidays do not count towards the...

                   Louisiana  \
 0                        72
 1                         2
 2                       NaN
 3  2022-06-16T13:15:50.000Z
 4                       NaN

                                                Texas  \
 0                                                 24
 1                                                  2
 2  The ultrasound must take place at least 24 hou...
 3                                                NaN
 4                                                NaN

                      Alaska  West Virginia
 0                       NaN           24.0
 1                         1            1.0
 2                       NaN            NaN
 3  2022-02-15T21:04:41.000Z            NaN
 4                       NaN            NaN

 [5 rows x 30 columns],
    Kentucky  Nevada  Alaska  New Hampshire  Nebraska  Wisconsin  Mississippi  \
 0       1.0     NaN     NaN            NaN       1.0        1.0          1.0
 1       1.0     NaN     NaN            1.0       1.0        1.0          1.0
 2      18.0     NaN     NaN           18.0      18.0       18.0         18.0
 3       1.0     NaN     NaN            1.0       1.0        1.0          2.0
 4       NaN     1.0     1.0            NaN       NaN        NaN          NaN
 5       NaN     NaN     NaN            1.0       NaN        NaN          NaN
 6       NaN     NaN     NaN            NaN       NaN        NaN          NaN

    Maine                 Minnesota  New York  ...                   Florida  \
 0    NaN                       NaN       NaN  ...                      True
 1    NaN                       NaN       NaN  ...                      True
 2    NaN                       NaN       NaN  ...                        18
 3    NaN                       NaN       NaN  ...                         1
 4    1.0                      True       1.0  ...                       NaN
 5    NaN                       NaN       NaN  ...                       NaN
 6    NaN  2022-08-23T13:46:39.000Z       NaN  ...  2022-08-23T13:40:32.000Z

    Arkansas  Missouri  Virginia  Rhode Island  Washington  Utah  Idaho Kansas  \
 0       1.0       1.0       1.0           1.0         NaN   1.0    1.0    1.0
 1       1.0       1.0       1.0           1.0         NaN   1.0    1.0    1.0
 2      18.0      18.0      18.0          18.0         NaN  18.0   18.0   18.0
 3       1.0       1.0       1.0           1.0         NaN   1.0    1.0    2.0
 4       NaN       NaN       NaN           NaN         1.0   NaN    NaN    NaN
 5       NaN       NaN       1.0           NaN         NaN   1.0    NaN    NaN
 6       NaN       NaN       NaN           NaN         NaN   NaN    NaN    NaN

    South Carolina
 0             1.0
 1             1.0
 2            17.0
 3             1.0
 4             NaN
 5             NaN
 6             NaN

 [7 rows x 51 columns],
                       Idaho           Pennsylvania                  Oklahoma  \
 0                      True                    NaN                       NaN
 1                  Physical  Major Bodily Function                       NaN
 2                         0                     24                         0
 3                      True                   True                      True
 4  2022-08-29T21:34:59.000Z                    NaN  2022-06-24T18:35:26.000Z
 5                       NaN                    NaN                       NaN

                    Virginia             Massachusetts Washington  Michigan  \
 0                       NaN                       NaN        NaN       NaN
 1                       Any                       Any        Any       NaN
 2                        26                        24         99      99.0
 3                      True                      True       True       1.0
 4  2022-02-15T21:04:54.000Z  2022-06-30T09:58:24.000Z        NaN       NaN
 5                       NaN      Lethal fetal anomaly        NaN       NaN

                Delaware Illinois               Maryland  ...  \
 0                   NaN      NaN                    NaN  ...
 1                   Any      Any                    Any  ...
 2                    99       99                     99  ...
 3                  True     True                   True  ...
 4                   NaN      NaN                    NaN  ...
 5  Lethal fetal anomaly      NaN  Serious fetal anomaly  ...

               West Virginia              Wisconsin                     Texas  \
 0                      True                    NaN                       NaN
 1                  Physical  Major Bodily Function                       NaN
 2                         0                     22                         0
 3                      True                   True                      True
 4  2022-09-16T18:01:16.000Z                    NaN  2022-07-02T10:05:28.000Z
 5      Lethal fetal anomaly                    NaN                       NaN

                Rhode Island Maine            North Carolina  \
 0                       NaN   NaN                       NaN
 1                       NaN   Any                       Any
 2                        99    99                        20
 3                      True  True                      True
 4  2019-07-02T11:33:41.000Z   NaN  2022-08-17T21:23:23.000Z
 5                       NaN   NaN                       NaN

                     Alabama               Mississippi  \
 0                       NaN                      True
 1                  Physical                       NaN
 2                         0                         0
 3                      True                      True
 4  2022-06-28T22:14:05.000Z  2022-07-07T09:30:33.000Z
 5                       NaN                       NaN

                    Missouri District of Columbia
 0                       NaN                  NaN
 1                  Physical                  Any
 2                         0                   99
 3                      True                 True
 4  2022-06-24T15:19:57.000Z                  NaN
 5                       NaN                  NaN

 [6 rows x 45 columns],
                      Iowa  New Mexico                Indiana  South Carolina  \
 0                    True         NaN                   True             1.0
 1                    True         NaN                   True             1.0
 2                    True         1.0                    NaN             NaN
 3                    True         1.0                    NaN             1.0
 4   Serious fetal anomaly         NaN                    NaN             NaN
 5                     NaN         1.0                    NaN             NaN
 6                     NaN         NaN               Physical             NaN
 7                     NaN         NaN                   True             1.0
 8                     NaN         NaN                   True             1.0
 9                     NaN         NaN  Major Bodily Function             NaN
 10                    NaN         NaN  Major Bodily Function             NaN
 11                    NaN         NaN                   True             NaN
 12                    NaN         NaN                   True             NaN
 13                    NaN         NaN                    NaN             NaN
 14                    NaN         NaN                    NaN             NaN
 15                    NaN         NaN                    NaN             NaN
 16                    NaN         NaN                    NaN             NaN
 17                    NaN         NaN                    NaN             NaN

     Arkansas  District of Columbia                California  Missouri  \
 0        1.0                   1.0                       NaN       1.0
 1        1.0                   1.0                       NaN       1.0
 2        NaN                   1.0                      True       NaN
 3        1.0                   1.0                       NaN       NaN
 4        NaN                   NaN                       NaN       NaN
 5        NaN                   NaN                      True       NaN
 6        NaN                   NaN                       NaN       NaN
 7        1.0                   NaN                       NaN       NaN
 8        1.0                   NaN                       NaN       1.0
 9        NaN                   NaN                       NaN       NaN
 10       NaN                   NaN                       NaN       NaN
 11       NaN                   NaN                       NaN       1.0
 12       NaN                   NaN                       NaN       NaN
 13       NaN                   NaN                      True       NaN
 14       NaN                   NaN  2019-11-13T12:10:29.000Z       NaN
 15       NaN                   NaN                       NaN       NaN
 16       NaN                   NaN                       NaN       NaN
 17       NaN                   NaN                       NaN       NaN

     Pennsylvania  Idaho  ...  Washington Nebraska  New Jersey  Minnesota  \
 0            1.0    1.0  ...         NaN      1.0         NaN        NaN
 1            1.0    1.0  ...         NaN      1.0         NaN        NaN
 2            NaN    NaN  ...         1.0      NaN         1.0        1.0
 3            1.0    NaN  ...         NaN      NaN         1.0        1.0
 4            NaN    NaN  ...         NaN      NaN         NaN        NaN
 5            NaN    NaN  ...         1.0      NaN         1.0        1.0
 6            NaN    NaN  ...         NaN      NaN         NaN        NaN
 7            1.0    1.0  ...         NaN      NaN         NaN        NaN
 8            1.0    1.0  ...         NaN      1.0         NaN        NaN
 9            NaN    NaN  ...         NaN      NaN         NaN        NaN
 10           NaN    NaN  ...         NaN      NaN         NaN        NaN
 11           NaN    1.0  ...         NaN      1.0         NaN        NaN
 12           NaN    NaN  ...         NaN      NaN         NaN        NaN
 13           NaN    NaN  ...         1.0      NaN         NaN        NaN
 14           NaN    NaN  ...         NaN      NaN         NaN        NaN
 15           NaN    NaN  ...         NaN      NaN         NaN        NaN
 16           NaN    NaN  ...         NaN      NaN         NaN        NaN
 17           NaN    NaN  ...         NaN      NaN         NaN        NaN

                     Illinois                     Maine  Delaware  Kentucky  \
 0                        NaN                       NaN       1.0       1.0
 1                        NaN                       NaN       1.0       1.0
 2                        NaN                       NaN       1.0       NaN
 3                        NaN                       NaN       1.0       NaN
 4                        NaN                       NaN       NaN       NaN
 5                       True                      True       NaN       NaN
 6                        NaN                       NaN       NaN       NaN
 7                        NaN                       NaN       NaN       NaN
 8                        NaN                       NaN       NaN       1.0
 9                        NaN                       NaN       NaN       NaN
 10                       NaN                       NaN       NaN       NaN
 11                       NaN                       NaN       NaN       1.0
 12                       NaN                       NaN       NaN       NaN
 13                      True                      True       NaN       NaN
 14  2019-07-02T11:35:00.000Z  2019-11-13T12:09:56.000Z       NaN       NaN
 15                       NaN                       NaN       NaN       NaN
 16                       NaN                       NaN       NaN       NaN
 17                       NaN                       NaN       NaN       NaN

     Vermont Oregon
 0       NaN    NaN
 1       NaN    1.0
 2       1.0    1.0
 3       1.0    NaN
 4       NaN    NaN
 5       1.0    1.0
 6       NaN    NaN
 7       NaN    NaN
 8       NaN    NaN
 9       NaN    NaN
 10      NaN    NaN
 11      NaN    NaN
 12      NaN    NaN
 13      NaN    1.0
 14      NaN    NaN
 15      NaN    NaN
 16      NaN    NaN
 17      NaN    NaN

 [18 rows x 51 columns]]

In [25]:
data_frame = pd.concat(content)

In [26]:
data_frame

,Kentucky,Oklahoma,Kansas,Ohio,Arizona,Mississippi,Tennessee,Wisconsin,Alabama,Missouri,...,Connecticut,Colorado,District of Columbia,Vermont,Illinois,New Mexico,Montana,Hawaii,Rhode Island,Washington
0,24.0,72.0,24.0,24.0,24.0,24.0,48.0,24.0,48,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,In cases of ectopic pregnancy or severe fetal ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,1.0,NaN,NaN,NaN,NaN,True,NaN,1.0,NaN
2,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0,...,NaN,18.0,NaN,NaN,NaN,NaN,18,NaN,18.0,NaN
3,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,...,NaN,1.0,NaN,NaN,NaN,NaN,1,NaN,1.0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,1.0,1.0,True,1.0,NaN,1.0,NaN,1.0
5,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2022-08-23T13:38:09.000Z,NaN,2022-02-11T15:51:59.000Z,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Physical,NaN,Physical,Physical,Any,NaN,Physical,Major Bodily Function,Physical,Physical,...,Any,NaN,Any,NaN,Any,NaN,Major Bodily Function,Any,NaN,Any
2,0,0,22,22,15,0,0,22,0,0,...,99,NaN,99,NaN,99,NaN,99,99,99,99
3,True,True,True,True,True,True,True,True,True,True,...,True,NaN,True,NaN,True,NaN,True,True,True,True
4,2022-08-02T11:56:07.000Z,2022-06-24T18:35:26.000Z,NaN,2022-09-14T21:34:20.000Z,2022-10-08T00:48:40.000Z,2022-07-07T09:30:33.000Z,2022-08-25T09:54:08.000Z,NaN,2022-06-28T22:14:05.000Z,2022-06-24T15:19:57.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-02T11:33:41.000Z,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1.0,1.0,True,1.0,True,True,1.0,True,1.0,1.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1,1.0,1.0,True,1.0,True,True,1.0,True,1.0,1.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0
3,NaN,NaN,NaN,1.0,True,True,1.0,True,1.0,NaN,...,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,NaN
4,NaN,NaN,NaN,NaN,NaN,Serious fetal anomaly,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,1.0,True,1.0,1.0,1.0,NaN,1.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Physical,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,1.0,NaN,True,NaN,True,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.0,1.0,True,1.0,True,True,NaN,True,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,Major Bodily Function,NaN,NaN,Physical,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1.0,1.0,True,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,1.0
14,NaN,NaN,2021-05-21T22:14:13.000Z,NaN,2021-05-21T22:18:09.000Z,NaN,NaN,2021-05-21T22:13:01.000Z,NaN,NaN,...,NaN,NaN,NaN,NaN,2019-07-02T11:35:00.000Z,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN